[package]
name = "RenderEngine"
version = "1.56.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#Pixels required libraries
pixels = "0.7.0"
winit = "0.25.0"
winit_input_helper = "0.10.0"
log = "0.4.14"