name: Build and Release
run-name: ${{ github.actor }} is creating a windows and linux build for release
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Installing dependencies
        run: |
          rustup target add x86_64-pc-windows-gnu
          apt intall mingw
      - name: Build Windows Release
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Build Linux Release
        run: cargo build --release
      - run: echo "This job's status is ${{ job.status }}."
