name: Build and Release
run-name: ${{ github.actor }} is creating a windows and linux build for release
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - workflow_debug

jobs:
  Build-and-Release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5


      - name: Get next version
        id: version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"

          # Check for explicit version e.g. "version: 1.2.0"
          EXPLICIT=$(echo "$COMMIT_MSG" | grep -oP 'version:\s*\K[0-9]+\.[0-9]+\.[0-9]+')

          if [ -n "$EXPLICIT" ]; then
            NEW_TAG="v$EXPLICIT"
          else
            LATEST=$(git tag --sort=-v:refname | head -n1)
            LATEST=${LATEST:-v0.0.0}
            MAJOR=$(echo $LATEST | cut -d. -f1 | tr -d v)
            MINOR=$(echo $LATEST | cut -d. -f2)
            PATCH=$(echo $LATEST | cut -d. -f3)

            if echo "$COMMIT_MSG" | grep -q "#major"; then
              NEW_TAG="v$((MAJOR + 1)).0.0"
            elif echo "$COMMIT_MSG" | grep -q "#minor"; then
              NEW_TAG="v$MAJOR.$((MINOR + 1)).0"
            else
              NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
            fi
          fi

          echo "Version: $NEW_TAG"
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT


      - name: Install dependencies
        run: |
          rustup target add x86_64-pc-windows-gnu
          sudo apt-get install -y mingw-w64


      - name: Build Linux Release
        run: |
          cargo build --release
          mv target/release/RenderEngine ./RenderEngine-linux
      - name: Build Windows Release
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          mv target/x86_64-pc-windows-gnu/release/RenderEngine.exe ./RenderEngine-windows.exe


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag }}
          name: Release ${{ steps.version.outputs.tag }}
          generate_release_notes: true  # auto-generates notes from commits/PRs
          files: |
            ./RenderEngine-linux
            ./RenderEngine-windows.exe

      - run: echo "This job's status is ${{ job.status }}."
