name: Test Workflow
run-name: ${{ github.actor }} is creating a windows and linux build for release
on:
  pull_request:
    types:
      - closed
    branches:
      - workflow_debug

jobs:
  Testing-workflow:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Get next version
        id: version
        env:
          LABELS_JSON: ${{ toJson(github.event.pull_request.labels) }}
          GH_TOKEN: ${{ github.token }}
        run: |
          LABELS=$(echo "$LABELS_JSON" | jq .[].name)
          echo "LABELS: \n$LABELS"
          LATEST=$(gh release view --json tagName --jq '.tagName')
          echo "Latest release: $LATEST"
          
          MAJOR=$(echo $LATEST | cut -d. -f1 | tr -d v)
          MINOR=$(echo $LATEST | cut -d. -f2)
          PATCH=$(echo $LATEST | cut -d. -f3)


          if echo "$LABELS" | grep -q "major"; then
            NEW_TAG="v$((MAJOR + 1)).0.0"
          elif echo "$LABELS" | grep -q "minor"; then
            NEW_TAG="v$MAJOR.$((MINOR + 1)).0"
          elif echo "$LABELS" | grep -q "patch"; then
            NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          fi

          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT
          echo "$NEW_TAG"


      # - name: Install dependencies
      #   run: |
      #     rustup target add x86_64-pc-windows-gnu
      #     sudo apt-get install -y mingw-w64


      # - name: Build Linux Release
      #   run: |
      #     cargo build --release
      #     mv target/release/RenderEngine ./RenderEngine-linux
      # - name: Build Windows Release
      #   run: |
      #     cargo build --release --target x86_64-pc-windows-gnu
      #     mv target/x86_64-pc-windows-gnu/release/RenderEngine.exe ./RenderEngine-windows.exe


      # - name: Create Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: ${{ steps.version.outputs.tag }}
      #     name: Release ${{ steps.version.outputs.tag }}
      #     generate_release_notes: true  # auto-generates notes from commits/PRs
      #     files: |
      #       ./RenderEngine-linux
      #       ./RenderEngine-windows.exe

      - run: echo "This job's status is ${{ job.status }}."
