name: Test Workflow
run-name: ${{ github.actor }} is creating a windows and linux build for release
on:
  pull_request:
    types:
      - closed
    branches:
      - workflow_debug

jobs:
  Testing-workflow:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5

      - name: Get next version
        id: version
        env:
          LABELS_JSON: ${{ toJson(github.event.pull_request.labels) }}
          GH_TOKEN: ${{ github.token }}
        run: |
          LABELS=$(echo "$LABELS_JSON" | jq .[].name)
          echo "LABELS: \n$LABELS"
          LATEST=$(gh release view --json tagName --jq '.tagName')
          echo "Latest release: $LATEST"
          
          MAJOR=$(echo $LATEST | cut -d. -f1 | tr -d v)
          MINOR=$(echo $LATEST | cut -d. -f2)
          PATCH=$(echo $LATEST | cut -d. -f3)

          if echo "$LABELS" | grep -q "major"; then
            NEW_TAG="v$((MAJOR + 1)).0.0"
          elif echo "$LABELS" | grep -q "minor"; then
            NEW_TAG="v$MAJOR.$((MINOR + 1)).0"
          elif echo "$LABELS" | grep -q "patch"; then
            NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          fi

          echo "New Release: $NEW_TAG"
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - run: echo "This job's status is ${{ job.status }}."
